### ISSUE TITLE
Read but no write

### ISSUE THREAD

**Issue by lee32768** [carbonsphere/UHPPOTE#11]
I've been able to poll the controller with 'dev_staus' and get good info back 
`Padding 56 Send the following command to network 17200000F5AD38190000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 Listening for return status Processing return status Array ( [index] => 5645 [swipeRecord] => 02 [noaccess] => 01 [doornum] => 02 [dooropen] => 01 [cardid] => 3955487144 [swipeymdhms] => 2019-10-05 09:35:13 [swipereason] => 2c [door1stat] => 01 [door2stat] => 01 [door3stat] => 01 [door4stat] => 01 [door1button] => 00 [door2button] => 00 [door3button] => 00 [door4button] => 00 [systemstat] => 00 [systemtime] => 09:35:28 [packetserial] => 00000000 [backup] => 00000000 [specialmsg] => 00 [battery] => 00 [fire] => 00 [systemdate] => 2019-10-05 )`

When I try to write via open_door, depending upon my format of the door number (leading zero) I'm met with an 'error/success' or 'unable to process' errors.

`Door: 2Array ( [door] => 2 ) Open Door Padding 55.5 Send the following command to network 17400000F5AD381920000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 There is an error: 0 -- Success`

`Door: 02Array ( [door] => 02 ) Open Door Padding 55 Send the following command to network 17400000F5AD38190200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 Listening for return status Processing return status Error: unable to process command. Unknown. 64 Array ( )`

Either way - I'm not getting an unlock command to the controller.  Am I missing something?
(I'm running a linux disty on a Pi3 now)

thanks
lee

1.

**Comment by carbonsphere** [comment]
'open_door' takes argument 'Door'=> '01'  or '02' or '03' or '04'
default: '01'   door 1
Your second command looks good, but the return is not recognized. 
could you insert var_dump($receive); on line 53 just under "public function procCmd($receive) {"
This way I can see what is being returned from the controller. 

Remember ($received) takes hex instead of binary.  You will have to pass in converted received data into procCmd.

**Comment by lee32768** [comment]
`Door: 02Array ( [door] => 02 ) Open Door Padding 55 Send the following command to network 17400000F5AD38190200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 Listening for return status Processing return status string(128) "17400000f5ad38190100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" Error: unable to process command. Unknown. 64 Array ( )`

here's the response with $receive dumped.

**Comment by carbonsphere** [comment]
would you post part of the code that you are using for getting return command?
This is from example.

/*
 * Once the command is sent to UHPPOTE controller board, now we need to listen for return status
 */
echo "Listening for return status\n";
$reply = getReturnPacket($sock);

/*
 * Process returned message. Returned message is in binary format
 * So we revert it into hex before passing into procMessages
 */
echo "Processing return status\n";
$procmsg = $a->procCmd(bin2hex($reply));

could you dump the "reply". in hex form would be best use var_dump(bin2hex($reply));

The dump you have only for the command that is being sent to the controller.

**Comment by carbonsphere** [comment]
I think I see the problem. Your door should open, it is just not handling the door open return

**Comment by carbonsphere** [comment]
Ok, it has been updated. Command sent to door controller should be ok. The door should open on command, it didn't handle the reply and that is why it displayed error, but by looking at the hex string. 01 returned is telling you that command sent was ok.  

Let me know if the door opened for you. If it works, then I'll close this.

**Comment by lee32768** [comment]
Thanks - I'm onsite tomorrow morning - so I'll update tonight and verify in the AM.

**Comment by lee32768** [comment]
That worked correctly now!  The door_open command mimics what happens when the controller receives a card swipe that has access.  The door relay actuates for the delay time and then returns to it's normal state.  There's another function, and I'm searching for the documentation now, that should allow the relay to be forced on and stay on - in the software it's called 'Normally Open' or forced off and stay off (called 'Normally Closed'), or respond to card swipes - which they call "Online".  I'm happy to close this thread and investigate that on my own (adding those functions) and report back.

Thanks again,
Lee

**Comment by carbonsphere** [comment]
Alrighty then.. Glad to hear.
I'm not aware of commands for normally open & close. Only normally close & open that i'm aware of is on the controller board ( at least on my board has it) where you have to physically wire it to the mag lock.  But do let me know if you find something  about it. I'm not sure if it can be controlled on the software side.  

There is "door_delay" that allows you to set the number of seconds that the door will stay open/close

**Comment by cvschleich** [comment]
This is actually something I'm working on. You have to change the mode from Door Controlled to Door Open. I hope to add this mode control to sendCommand in the next few weeks.
