### ISSUE TITLE
monitor.php - Address already in use

### ISSUE THREAD

**Issue by erichegit** [carbonsphere/UHPPOTE#13]
I am happy with this examples, but if I want to use monitor.php, I receive following message in my webbrowser

**Listening for return status Processing return status bool(true) Could not bind socket : [98] Address already in use**

PHP is running on my Raspberry Pi.

```
/*
 * The ip address and port of this machine tht will receive 
 * monitor messages
 */

$localip = "192.168.1.100"; // is this the IP-Address of my Raspberry Pi = ????
$localport = 60003;
```
What can I try to get the monitoring work?

**Comment by carbonsphere** [comment]
Hi,
Yes localip & localport is suppose to set your controller to start forwarding card swipe status to that address. If you are using your raspberry pi, then it will be raspberry pi's IP address and port. Check your port and ip, there might be something that uses it already. Be sure you didn't run 2 instances or other program that listens at the same port.
