### ISSUE TITLE
Invalid HEX conversion when using Uhppote.php outside of command line

### ISSUE THREAD

**Issue by realashleybailey** [carbonsphere/UHPPOTE#14]
When using the Uhppote.php file outside of a command line terminal using the 
```php
$cmd = $a->getCmdHex($argv[3], $dt, $data);
``` 
command the `$data` variable that stores the door number when using the `open_door` command changes the door value from **01, 02, 03 or 04** to **1, 2, 3, 4** causing the HEX conversion to not be valid length, to fix this we can check the value on on input at line **751** of of the **Uhppote.php** file from 
```php
$hexStr .= (isset($param['door']) ? $param['door'] : '01');
``` 
**to**
```php
$hexStr .= (isset($param['door']) ? ((substr($param['door'], 0, 1) == 0) ? $param['door'] : 0 . $param['door']) : '01');
``` 
we use substr to check if the input begins with a '0' and if not then we pad it with a '0' before using it.

This is my first time submitting an issue on Github, so if Im doing this all wrong I apologize just let me know. :)

**Comment by carbonsphere** [comment]
$data['door'] should be a string instead of integer. 

ex: $data['door'] = '01'  instead of $data['door'] = 01;

However, I'll still add a check, just incase user decides to use integer instead of string. 

Added value check to determine int or str for door parameter.
