### ISSUE TITLE
sendCommand doesn't complete task

### ISSUE THREAD

**Issue by Uzzi** [carbonsphere/UHPPOTE#15]
Hi, I've send this:
php -f sendCommand.php <default IP> <sn> set_ip <new IP> <new subnet mask> <new gataway>
This is output:
Padding 40

Script doesn't end fine.
Can you help me?

**Comment by cvschleich** [comment]
set_ip requires the IP address on the command line. Having said that, it should have printed the help text. But try adding the IP on the command line and see if it does what it's supposed to for you.

**Comment by Uzzi** [comment]
sorry i've write wrong:
php -f sendCommand.php  ACTUALIP SN set_ip NEWIP NEWSNETMASK NEWGATEWAY

**Comment by cvschleich** [comment]
Can you copy/paste the output on the screen (do anonymize the IPs and SN before posting)?

**Comment by Uzzi** [comment]
pi@rasperry:\php -f sendCommand.php 192.168.0.0 0000000b set_ip 0.0.0.2 255.255.255.0 0.0.0.1
Padding 40

**Comment by carbonsphere** [comment]
you seem to be on RPI, try running the command in root. It seems to be hanging in socket_create, if you only see Padding 40. You can also turn on the debug flag at the beginning of the script to see where.

**Comment by carbonsphere** [comment]
Make sure your board is on the same network. The program will wait for return message from the device. If device doesn't send a return message, then the program will just wait.  You can change the debug flag to 1. This will show if your program is stopped at waiting state if you see "Listening for return status". You have to make sure that the command is being received by your device by logging the packets.

**Comment by Uzzi** [comment]
new ip is on other subnet, then it write new ip, but feedback is not recived on old subnet
Thank you
