### ISSUE TITLE
Hex Error

### ISSUE THREAD

**Issue by prestonmainard** [carbonsphere/UHPPOTE#2]
I'm having a problem when trying to run example.php (or any file where it's sending). This is the error that is being thrown: 

Warning: hex2bin(): Hexadecimal input string must have an even length

**Comment by carbonsphere** [comment]
Make sure you follow the direction on setting your serial number from board.

 * Remember to set your serial number
 * usually the last 4 bytes of your board's MAC address
 * EX:  00:11:22:33:44:55  then the Serial Number = 22334455
